[tool.poetry]
name = "fer"
version = "0.2.0"
description = ""
authors = ["Samuel Oliveira <patriciosamuel097@gmail.com>"]
license = "Science Code"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
numpy = "^2.2.6"
